version: '3.1'

services:

    db:
        image: postgres
        restart: always
        environment:
            POSTGRES_USER: pguser
            POSTGRES_PASSWORD: example
            POSTGRES_DB: warsztat

        ports:
            - 5432:5432

    adminer:
        image: adminer
        restart: always
        ports:
            - 8484:8080
